name: Check issues metadata

on:
  issues:
    types: [ opened, unlabeled, closed ]

jobs:
  check_issue_metadata:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # Check that issues have proper metadata: labels and milestone
      # https://github.com/gradle/issue-management-action/blob/main/src/issue-metadata.ts
      - uses: gradle/issue-management-action@v1
        with:
          script: "issue-metadata"
