name: Check pulls metadata

on:
  pull_request_target:
    types: [ closed ]

jobs:
  check_pull_metadata:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      # Check that PRs have proper metadata: labels and milestone
      # https://github.com/gradle/issue-management-action/blob/main/src/pull-metadata.ts
      - uses: gradle/issue-management-action@v1
        with:
          script: "pull-metadata"
